# Build settings
name: my-portfolio-2017

markdown: kramdown
permalink: pretty

baseurl: /my-portfolio-2017
url: http://crystalcastles.github.io

sass:
  sass_dir: assets/css
  style: :nested
  
# jekyll serve --watch -H $IP -P $PORT --baseurl ""